### ISSUE TITLE
Less then 25 Images.

### ISSUE THREAD

**Issue by TJ4RK** [jportella93/reddit-image-downloader#1]
Hi,
apperently the code doesnt download more then 25 images at a time, even if you set maxPictures to something greater then 25, is there a particular reason for that? ^^;

**Comment by jportella93** [comment]
Hey! It's the default reddit's limit... I can modify the code to can crank it up until a 100, that's the actual limit, how does that sound?

**Comment by TJ4RK** [comment]
If that wouldnt be to much of a hassle, that would be a great thing ^^

**Comment by jportella93** [comment]
Done, let me know if that works for you

**Comment by TJ4RK** [comment]
Works perfect now. Thanks alot :D
